### ISSUE TITLE
Testes unitários e de integração

### ISSUE THREAD

**Issue by alexradavelli** [LuizHenrique000/ProjetoLP2#1]
- Seria interessante cobrir a camada de negócio com testes unitários
- Seria interessante implementar ao menos um teste de integração

**Comment by alexradavelli** [comment]
Para testes de integração é recomendável utilizar o MockMvc do Spring, pois ele consegue simular as requisições HTTP. Já para testes unitários, pode utilizar apenas o JUnit. Se quiser, dá uma olhada no framework Mockito, para mockar as dependências das services.

https://site.mockito.org/
https://www.baeldung.com/mockito-annotations

**Comment by LuizHenrique000** [comment]
Concluída!!!
