### ISSUE TITLE
Validação na sintáxe de corpo de requisições

### ISSUE THREAD

**Issue by alexradavelli** [LuizHenrique000/ProjetoLP2#3]
É interessante utilizar a API de validação do Java (javax.validation) para implementar a validação da sintáxe de atributos dos corpos das requisições, especialmente em requisições POST e PUT. Neste contexto, é possível validar:

- Atributos obrigatórios
- Tamanho dos atributos
- Formato dos atributos
- Domínio dos valores válidos para os atributos
- Entre outros casos

**Comment by LuizHenrique000** [comment]
Concluído!!!
