### ISSUE TITLE
Implementar tratamento para outros tipos de erro HTTP

### ISSUE THREAD

**Issue by alexradavelli** [LuizHenrique000/ProjetoLP2#4]
https://github.com/LuizHenrique000/ProjetoLP2/blob/2bc902631d9056d36dc951fb711c949ec9391610/projetoLP2/src/main/java/com/fundatec/lp2/controller/exceptions/ControllerExceptionHandler.java#L15

**Comment by LuizHenrique000** [comment]
Concluída!!!
